PROG =	rxspencer_grep
SRCS =	libc_grep.c

.PATH:		../libc_grep
.NOPATH:	libc_grep.o

CPPFLAGS +=	${RXSPENCER_CPPFLAGS}
LDADD    +=	${RXSPENCER_LDADD}
LDFLAGS  +=	${RXSPENCER_LDFLAGS}

.include <mkc.mk>
